export enum FeatureFlag {
  FF_LOG_SERVEUR = "FF_LOG_SERVEUR",
  FF_DELIVRANCE_CERTIFS_SITUATIONS = "FF_DELIVRANCE_CERTIFS_SITUATIONS",
  FF_DELIVRANCE_EXTRAITS_COPIES = "FF_DELIVRANCE_EXTRAITS_COPIES",
  FF_INTEGRATION_CIBLE_REQUETE_NATURALISATION = "FF_INTEGRATION_CIBLE_REQUETE_NATURALISATION",
  FF_SIGNER_ACTE_ETABLISSEMENT = "FF_SIGNER_ACTE_ETABLISSEMENT",
  FF_DELIVRANCE_EXTRAITS_COPIES_VIA_SAGA = "FF_DELIVRANCE_EXTRAITS_COPIES_VIA_SAGA"
}
