export enum FeatureFlag {
  FF_LOG_SERVEUR = "FF_LOG_SERVEUR",
  FF_DELIVRANCE_CERTIFS_SITUATION = "FF_DELIVRANCE_CERTIFS_SITUATION",
  FF_DELIVRANCE_EXTRAITS_COPIES_VIA_SAGA = "FF_DELIVRANCE_EXTRAITS_COPIES_VIA_SAGA",
  FF_INTEGRATION_CIBLE_REQUETE_NATURALISATION = "FF_INTEGRATION_CIBLE_REQUETE_NATURALISATION",
  FF_SIGNER_ACTE_ETABLISSEMENT = "FF_SIGNER_ACTE_ETABLISSEMENT",
  FF_UTILISER_NOUVELLE_RMC = "FF_UTILISER_NOUVELLE_RMC",
  FF_SIMULER_SIGNATURE = "FF_SIMULER_SIGNATURE"
}
