import { IPersonne } from "@model/etatcivil/commun/IPersonne";
import { TypeRedactionActe } from "../../enum/TypeRedactionActe";
import { ICorpsExtraitRectification } from "../ICorpsExtraitRectification";
import { ICorpsText } from "../ICorpsText";
import { IDeclarant } from "../IDeclarant";
import { IDetailMariage } from "../IDetailMariage";
import { IEvenement } from "../IEvenement";
import { IRegistre } from "../IRegistre";
import { ICorpsImage } from "../imageActe/ICorpsImage";
import { IMention } from "../mention/IMention";
import { IProjetAnalyseMarginale } from "./IAnalyseMarginaleProjetActe";
import { ITitulaireProjetActe } from "./ITitulaireProjetActe";

export interface IProjetActe {
  id: string;
  titulaires: ITitulaireProjetActe[];
  evenement?: IEvenement;
  nature: string;
  numero: string;
  numeroBisTer: string;
  personnes: IPersonne[];
  estReecrit?: boolean;
  registre: IRegistre;
  dateDerniereMaj?: Date;
  dateDerniereDelivrance?: Date;
  dateCreation?: Date;
  visibiliteArchiviste: string;
  analyseMarginales?: IProjetAnalyseMarginale[];
  detailMariage?: IDetailMariage;
  corpsTexte?: ICorpsText;
  corpsImage?: ICorpsImage;
  type: string;
  corpsExtraitRectifications: ICorpsExtraitRectification[];
  mentions: IMention[];
  sexe: string;
  declarant?: IDeclarant;
  reconnuPar?: string;
  numeroDossierNational?: string;
  statut: string;
  dateStatut: Date;
  dateInitialisation: Date;
  modeCreation?: TypeRedactionActe;
}
