import ETypeDeclarationConjointe from "@model/etatcivil/enum/ETypeDeclarationConjointe";
import { IAdresse } from "../IAdresse";
import { IDecretNaturalisation } from "../IDecretNaturalisation";
import { IEvenement } from "../IEvenement";
import { IFiliationProjetActeTranscrit } from "./IFiliationProjetActe";
export interface ITitulaireProjetActe {
  nom?: string;
  ordre: number;
  prenoms?: string[];
  sexe: string;
  naissance?: IEvenement;
  age?: number | null;
  profession?: string;
  domicile?: IAdresse;
  filiations: IFiliationProjetActeTranscrit[];
  nomPartie1?: string;
  nomPartie2?: string;
  nomAvantMariage?: string;
  nomApresMariage?: string;
  nomDernierConjoint?: string;
  prenomsDernierConjoint?: string;
  typeDeclarationConjointe?: keyof typeof ETypeDeclarationConjointe;
  dateDeclarationConjointe?: Date;
  origineDeclarationConjointeTitulaireActe?: boolean;
  origineNomPartiesTitulaireActe?: boolean;
  identiteAvantDecret?: string;
  decretNaturalisation: IDecretNaturalisation | null;
  pasDePrenom: boolean;
  reconnuPar?: string;
}
