export const CODE_CERTIFICAT_SITUATION_PACS = "CERTIFICAT_SITUATION_PACS";
export const CODE_CERTIFICAT_SITUATION_PACS_RC = "CERTIFICAT_SITUATION_PACS_RC";
export const CODE_CERTIFICAT_SITUATION_PACS_RCA =
  "CERTIFICAT_SITUATION_PACS_RCA";
export const CODE_CERTIFICAT_SITUATION_PACS_RC_RCA =
  "CERTIFICAT_SITUATION_PACS_RC_RCA";
export const CODE_CERTIFICAT_SITUATION_RC = "CERTIFICAT_SITUATION_RC";
export const CODE_CERTIFICAT_SITUATION_RCA = "CERTIFICAT_SITUATION_RCA";
export const CODE_CERTIFICAT_SITUATION_RC_RCA = "CERTIFICAT_SITUATION_RC_RCA";
export const CODE_ATTESTATION_PACS = "ATTESTATION_PACS";
export const CODE_CERTIFICAT_INSCRIPTION_RC = "CERTIFICAT_INSCRIPTION_RC";
export const CODE_CERTIFICAT_INSCRIPTION_RCA = "CERTIFICAT_INSCRIPTION_RCA";

export const INFORMATION_DIVERSES_MANQUANTE = "CARN_EC_117";
export const MANDAT_GENEALOGIQUE = "CARN_EC_18";
export const JUSTIFICATIF_REPRESENTANT_MANQUANT = "CARN_EC_19";
export const ACTE_NON_TROUVE = "CARN_EC_115";
export const ACTE_NON_TROUVE_ALGERIE = "CARN_EC_64";
export const ACTE_NAISSANCE_NON_TROUVE_MARIAGE = "CARN_EC_24";
export const ATTESTATION_PENSION = "CARN_EC_APR";
export const PROPOSITION_TRANSCRIPTION = "CARN_EC_PTA";
export const DIVERS = "CARN_EC_17";
export const REFUS_DELIVRANCE_MARIAGE = "CARN_EC_RDM";
export const DELIVRANCE_ACTE_NON_ANTHENTIQUE = "CAD_ARCH_118";
export const DELIVRANCE_ACTE = "CAD_EC_116";
export const DELIVRANCE_ACTE_INCOMPLET = "CAD_EC_50";

export const CODE_COPIE_INTEGRALE = "COPIE_INTEGRALE";
export const CODE_COPIE_NON_SIGNEE = "COPIE_NON_SIGNEE";
export const CODE_DECISION_PROTECTION = "DECISION_PROTECTION";
export const CODE_EXTRAIT_AVEC_FILIATION = "EXTRAIT_AVEC_FILIATION";
export const CODE_EXTRAIT_PLURILINGUE = "EXTRAIT_PLURILINGUE";
export const CODE_EXTRAIT_SANS_FILIATION = "EXTRAIT_SANS_FILIATION";
