export enum QualiteFamille {
  PARENT = "PARENT",
  FRATRIE = "FRATRIE",
  ANCIEN_CONJOINT = "ANCIEN_CONJOINT",
  CONJOINT_ACTUEL = "CONJOINT_ACTUEL",
  ENFANT_MINEUR = "ENFANT_MINEUR",
  ENFANT_MAJEUR = "ENFANT_MAJEUR",
  PARENT2ENFANT = "PARENT2ENFANT"
}
