import { eachLike } from "@pact-foundation/pact/dsl/matchers";

export const requetesPact = eachLike({
  idRequete: "c456358c-6e4c-4a5f-adc3-083e692f72ab",
  idSagaDilaImpression: null,
  idSagaDila: 1,
  idRequeteInitiale: null,
  identifiantPartenaire: "A-1-XZ1WOMAX",
  dateCreation: 1591803760,
  dateDerniereMaj: 1591803760,
  canal: "INTERNET",
  provenance: "DILA",
  statut: "A_SIGNER",
  dateStatut: 1599472699.838561,
  dateTrtDemat: null,
  dateDelivranceDemat: null,
  typeRequete: "DELIVRANCE",
  sousTypeRequete: "RDD",
  natureActe: "NAISSANCE",
  typeActe: "EXTRAIT_AVEC_FILIATION",
  jourEvenement: 25,
  moisEvenement: 3,
  anneeEvenement: 1983,
  villeEvenement: "paris",
  paysEvenement: "france",
  nbExemplaire: null,
  motifRequete: "PENSION_REVERSION",
  lienRequerant: null,
  mandantType: null,
  mandantIdentite: null,
  mandantLien: null,
  piecesJustificatives: eachLike({
    idPieceJustificative: "c456939a-09ad-4a94-8dd2-0425b22ff4c4",
    nom: "1_c45606fb-f0e3-4647-ab4a-a6c5c416e809.pdf",
    mimeType: "application/pdf",
    typePieceJustificative: "cpro",
    extension: null,
    taille: 207836,
    contenu: null,
    conteneurSwift: "pieces-justificatives-2020-6",
    requete: null
  }),
  reponse: {
    idReponse: "c45640ba-364e-4bd5-a8e7-4d4a0066ef87",
    dateTraitementDemat: null,
    dateDelivrance: 1591862400,
    natureActe: "NAISSANCE",
    referenceActe: "(COL) ORAN.1961.RET ..12404",
    jourEvenement: 11,
    moisEvenement: 3,
    anneeEvenement: 1960,
    villeEvenement: "fez",
    paysEvenement: "maroc",
    nomOec: "SLAOUI",
    prenomOec: "Nabil",
    commentaire: "commentaire",
    documentsDelivres: eachLike({
      idDocumentDelivre: "c456bb58-04f5-40dd-8c33-599306cafb7d",
      typeDocument: "EXTRAIT_SANS_FILIATION",
      nom: "1_c4565512-1193-4f7d-88fd-042f75ca8364.pdf",
      mimeType: "application/pdf",
      taille: 207836,
      contenu: null,
      conteneurSwift: "documents-delivres-2020-6",
      reponse: null,
      cheminFs: "/saga-docinternet-fs/EXTRAIT.pdf"
    }),
    requete: null
  },
  requerant: {
    idRequerant: "c456e268-34c9-45df-9ffc-817d2ba081f2",
    typeRequerant: "TITULAIRE",
    qualiteRequerant: "PARTICULIER",
    nomInstitutionnel: null,
    identite: null,
    raisonSociale: null,
    nomFamille: "aubin",
    nomUsage: null,
    prenom: "nicolas",
    mail: null,
    telephone: "1777327569",
    adresse: null,
    requete: null
  },
  titulaires: eachLike({
    idTitulaire: "c4562f1c-08ad-45d9-b63e-4a3c391496d1",
    position: 1,
    nomNaissance: "aubin",
    nomUsage: null,
    prenom1: "nicolas",
    prenom2: "",
    prenom3: "",
    jourNaissance: 25,
    moisNaissance: 3,
    anneeNaissance: 1983,
    villeNaissance: "fez",
    paysNaissance: "maroc",
    adoption: null,
    sexe: null,
    parent1: null,
    parent2: null,
    requete: null
  })
});
